# Generated by Django 5.0.3 on 2024-03-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
